apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: users
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 1
  configs:
    cleanup.policy: "compact"
---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: datagen-users
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: "users"
    quickstart: "users"
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    key.converter.schemas.enable: "true"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    value.converter.schemas.enable: "true"
    max.interval: "1000"
    iterations: "10000000"
